test workflow

diff --git a/.github/workflows/bog_pay_app.yml b/.github/workflows/bog_pay_app.yml
--- a/.github/workflows/bog_pay_app.yml
+++ b/.github/workflows/bog_pay_app.yml
@@ -14,6 +14,19 @@ jobs:
     runs-on: ubuntu-latest
     
     steps:
+    - name: Checkout
+      uses: actions/checkout@v4
+      
+    - name: Manually clone mol_icon with retry
+      run: |
+        mkdir -p mol/icon
+        for i in {1..5}; do
+          git clone --depth 1 --single-branch https://github.com/nin-jin/mol_icon.git mol/icon && break || {
+            echo "Attempt $i failed, retrying..."
+            rm -rf mol/icon
+            sleep 5
+          }
+        done
     
     - name: Configure Git timeout
       run: |
